development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: <%= ENV['LCTV_DATABASE_NAME'    ] %>
  username: <%= ENV['LCTV_DATABASE_LOGIN'   ] %>
  password: <%= ENV['LCTV_DATABASE_PASSWORD'] %>
